#!/bin/sh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.

# Change your keymap:
xmodmap "/home/dmitry/.Xmodmap"
setxkbmap -layout us -variant mac -option altwin:swap_lalt_lwin

# Applications you want to run with fluxbox.
# MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN ''&'' AT THE END.
#
# unclutter -idle 2 &
# wmnd &
# wmsmixer -w &
# idesk &

gnome-settings-daemon &
nm-applet &
gnome-sound-applet &
workrave &
fbsetbg /usr/share/backgrounds/warty-final-ubuntu.png
/opt/screencloud/screencloud.sh &

[ -f ${HOME}/.fluxbox/local-startup ] && ${HOME}/.fluxbox/local-startup

# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.

exec fluxbox
# or if you want to keep a log:
# exec fluxbox -log "/home/dmitry/.fluxbox/log"
