#!/bin/sh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.

# Change your keymap:
xmodmap "/home/dmitry/.Xmodmap"
setxkbmap -layout us -variant mac -option altwin:swap_lalt_lwin

# Applications you want to run with fluxbox.
# MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN ''&'' AT THE END.
#
# unclutter -idle 2 &
# wmnd &
# wmsmixer -w &
# idesk &

(sleep 10 && dropboxd start) &
(sleep 15 && gnome-sound-applet) &
fbsetroot -foreground '#B2B2BF' -background '#B2B2BF' -solid '#B2B2BF'

# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.

exec fluxbox
# or if you want to keep a log:
# exec fluxbox -log "/home/dmitry/.fluxbox/log"
